pipeline:
  build:
    image: centos:7
    commands:
      - yum install -y wget gcc make openssl-devel
      - mkdir curl
      - wget -O - https://curl.haxx.se/download/curl-7.61.0.tar.gz|tar --strip 1 -xzC curl
      - cd curl
      - ./configure --disable-shared --enable-static
      - make -j2

  github-release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: "curl/src/curl"
    checksum:
      - sha256
    when:
      event: tag
